tokenizer: "/home/shreyas/NLP/dna2vec/src/model/tokenizers/dna_tokenizer_10k.json"

# initialized-with-one-step: "/mnt/SSD5/pholur/checkpoints/checkpoint_initalialized.pt"
# trained-ch2-1000: "/mnt/SSD5/pholur/checkpoints/checkpoint_smooth-rock-29.pt"
# trained-ch2-1000: "/mnt/SSD5/pholur/checkpoints/checkpoint_amber-elevator-53.pt"
trained-ch2-longer: "/mnt/SSD1/shreyas/dna2vec/checkpoint_rich-fog-63.pt"

# trained-all: "/mnt/SSD2/pholur/General_Models/checkpoint_exalted-dew-60.pt"
trained-all-longer: "/mnt/SSD5/pholur/checkpoints/checkpoint_major-flower-62.pt"

trained-all-shorter: "/mnt/SSD5/pholur/checkpoints/vocal-paper-2.pt"

trained-all-reg-mean-pooling: "/home/shreyas/NLP/dna2vec/models/regularization_0.0_pool_1020mean_checkpoint.pt"
trained-ch2-reg-mean-pooling: "/home/shreyas/NLP/dna2vec/models/chromosome_20.0_pool_1020_ART_READSmean_checkpoint.pt"
trained-all-reg-mean-pooling-mid: "/home/shreyas/NLP/dna2vec/models/regularization_0.0_pool_1020_ART_READS_mean_checkpoint.pt"
trained-all-reg-mean-pooling-nnsp: "/home/shreyas/NLP/dna2vec/models/regularization_0.0_pool_1020_ART_READS_mean_checkpoint.pt"
trained-all-reg-mean-pooling-lrg: "/home/shreyas/NLP/dna2vec/models/regularization_0.0_pool_1024_ART_READS_16heads_mean_checkpoint.pt"
trained-all-reg-cls: "/home/shreyas/NLP/dna2vec/models/regularization_0.0_pool_cls_checkpoint.pt"

dna2bert-mean: "Baseline"
dna2bert-max: "Baseline"
nucleotide-transformer-max: "Baseline"
nucleotide-transformer-mean: "Baseline"
hyena-dna-mean: "Baseline"
hyena-dna-max: "Baseline"



