defaults:
  - _self_

# Base configuration variables
base_settings:
  chromosome: "ch2"  # Set the chromosome number here
  reference: "NC-000002" #hs37d5 # Set the reference genome here
  base_path: "/home/mehmet/codebase/dna2vec"  # Base path for all other paths
  data_path: "/mnt/SSD7/yigit/dnarde"

experiment_settings:
  chr_number: 2  # Matches the chromosome set above
  type_of_sv: "all" # "insertion", "deletion", "skipped_region", "soft_clip", "all"
  size_of_sv: 50 # Size of the structural variant
  max_reads: 1000000 # Maximum number of reads to simulate

# All settings below will derive from the chromosome and reference settings
vector_db:
  # - ${base_settings.chromosome}-${base_settings.reference}-1300
  - ${base_settings.chromosome}-${base_settings.reference}

model:
  - huggingface  # Model used to generate embeddings

num_reads: 200  # Number of reads to test
system: MSv3  # Sequencing system for testing
device: cuda:0

namespace: true
no_namespace: false

reads:
  - ${base_settings.chromosome}-${base_settings.reference}  # Derived from chromosome setting

compare_type: both  # Type of comparison [location, score, both]
pod_type: s1.x4  # Pod type for testing (if creating a new index)
test_mode: true
return_type: score  # Return type [best_alignment, all_alignments, score]

path_to_real_reads: "to be added"
global_read_namespace_id: "to be added"

# Paths derived from base_path
paths:
  dna2vec_cache_dir: "${base_settings.base_path}"
  log_dir: "${base_settings.base_path}/Logs"
  meta_headers: "${base_settings.data_path}/${base_settings.chromosome}/headers_${base_settings.chromosome}"
  bam_file: "${base_settings.data_path}/rde2/HG002.${base_settings.reference}.2x250.bam"
  bed_path: "/home/mehmet/codebase/dna2vec/HG002_SVs_Tier1_v0.6.bed"

grid_search:
  read_length: [250]  # ART max read length
  insertion_rate: [0.01]  # ART max insertion rate
  deletion_rate: [0.01]  # ART max deletion rate
  qq: [[60, 90]]  # Quality score ranges
  topk: [75]
  distance_bound: [15]  # Score threshold
  exactness: [2]  # Index threshold

configs:
  raw_fasta_files: "${base_settings.data_path}/${base_settings.chromosome}/${base_settings.reference}.fasta"