defaults:
  - defaults/upsert_config_defaults.yaml
  - _self_

# set your own parameters here
vector_db: ["ch2"]
model: ["huggingface"]
device: "cuda:0"
add_namespace: true
no_namespace: false
recipes: ["ch2"]
pod_type: "s1.x1"
checkpoints : ["huggingface"]
data_recipes:
  ch2:
    - /mnt/SSD3/yigit/dna_data/chromosome_2/floodfill.txt
